# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "Rakefile"
    - "bin/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - !ruby/regexp /config\/(?!initializers\/(circuitbox|sidekiq|stripe)\.rb)/
    - "db/schema.rb"
    - "db/migrate/*"
    - "docker-compose.yml"
    - "Dockerfile"
    - "Gemfile"
    - "Gemfile.lock"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Include:
    - "app/**/*.rb"
    - "config/**/*.rb"
    - "lib/**/*.rb"
    - "spec/**/*.rb"
    - "test/**/*.rb"
    - "Gemfile"
