default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  url: postgresql://postgres:password@db/rx_orders_development

test:
  url: postgresql://postgres:password@db/rx_orders_test
